### ISSUE TITLE
Scraping breaks beyond a point.

### ISSUE THREAD

**Issue by raghunayyar** [arc298/instagram-scraper#108]
I am running this to scrape New York by location id.

`instagram-scraper --location 212988663 --maximum 100000 --media_metadata --media_types none`

After sometime, I get this issue:

```
Searching 212988663 for posts: 674 media [00:28,  5.88 media/s]ERROR: Failed to query 212988663
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/instagram_scraper/app.py", line 238, in __query_gen
    nodes, end_cursor = self.__query(url, entity_name, query, end_cursor)
  File "/Library/Python/2.7/site-packages/instagram_scraper/app.py", line 248, in __query
    payload = json.loads(resp.text)['data'][entity_name]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 42217 (char 42216)
```

**Comment by ChrisCintron** [comment]
I'll look into it tomorrow, however, if you need an immediate fix, it works for 3.5.

**Comment by raghunayyar** [comment]
Tried running this on python 3.6 and it still breaks :(
`instagram-scraper --location 212988663 --maximum 100000 --media_metadata --media_types none`

```
Searching 212988663 for posts: 3093 media [02:08, 24.15 media/s]ERROR: Failed to query 212988663
Traceback (most recent call last):
  File "/Users/raghunayyar/Documents/Development/instagram-scraper/instagram_scraper/app.py", line 238, in __query_gen
    nodes, end_cursor = self.__query(url, entity_name, query, end_cursor)
  File "/Users/raghunayyar/Documents/Development/instagram-scraper/instagram_scraper/app.py", line 248, in __query
    payload = json.loads(resp.text)['data'][entity_name]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 42024 (char 42023)
Searching 212988663 for posts: 3149 media [02:09, 24.35 media/s]
➜  instagram_scraper git:(master) ✗ 
```

**Comment by ChrisCintron** [comment]
I was wrong. It's broken for 3.5 as well.

**Comment by VasiliPupkin256** [comment]
I've got this issue today. It wasn't reproduced on the same account on the next run.

**Comment by KobaKhit** [comment]
I have been experiencing the same issue today.

**Comment by raghunayyar** [comment]
yeah, its weird because this issue comes sometimes and doesn't the other.

**Comment by AlexNik** [comment]
Debug output was added #732
Try to use the instagram-scraper with login credentials.
