### ISSUE TITLE
Fails when trying to download, was working till last week.

### ISSUE THREAD

**Issue by dashrath1526** [arc298/instagram-scraper#561]
Traceback (most recent call last):
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00DD41B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00DD41B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\Scripts\instagram-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.8.1', 'console_scripts', 'instagram-scraper')())
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper-1.8.1-py3.6.egg\instagram_scraper\app.py", line 1579, in main
    scraper.authenticate_as_guest()
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_scraper-1.8.1-py3.6.egg\instagram_scraper\app.py", line 237, in authenticate_as_guest
    req = self.session.get(BASE_URL)
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Dashrath Chauhan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00DD41B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by balibebas** [comment]
IG user content is now gated and available to authenticated users only via official APIs. Long story short: Scraping no longer works unless you're logged-in. You can confirm this by attempting to open any it asset on IG such as this one used in an example for the oEmbed functionality: https://www.instagram.com/p/fA9uwTtkSN/

https://developers.facebook.com/blog/post/2020/07/01/platform-terms-developer-policies/
https://developers.facebook.com/docs/instagram

**Comment by balibebas** [comment]
IG user content is now gated and available to authenticated users only via official APIs. Long story short: Scraping no longer works unless you're logged-in. You can confirm this by attempting to open any asset on IG, such as this one used in an example for the oEmbed functionality: https://www.instagram.com/p/fA9uwTtkSN/

https://developers.facebook.com/blog/post/2020/07/01/platform-terms-developer-policies/
https://developers.facebook.com/docs/instagram

**Comment by Aaronzinhoo** [comment]
This is just considering user content and not hashtags though correct ?
Instagram is getting really strict with their content now...

**Comment by balibebas** [comment]
I think it may be all content. For ideas on how to implement a fix the following JavaScript library may be helpful: https://github.com/oorestisime/gatsby-source-instagram. This library used to scrape content and had the same issue. They've already deprecated all scraping APIs and moved over to using the Instragram Graph API and left some instructions on how to set that up.

**Comment by dashrath1526** [comment]
Yeah,  I think there is no way now to scrap data as Guest user, even with the use of Display API, particular target page,hashtag,user account owner will have to provide access to their data.

**Comment by balibebas** [comment]
Could take a look at [Aurora Store](https://auroraoss.com/) codebase and how they mirror datasets. It's not the scale of IG, mind you. But I doubt most people would want datasets that large anyway. Alternatively you could create a faux user with crypton.sh for scraping purposes.

**Comment by dashrath1526** [comment]
When you said about faux user, did you mean for IG?
