### ISSUE TITLE
Can't retrieve all images from hashtag

### ISSUE THREAD

**Issue by abindadna** [arc298/instagram-scraper#562]
Why can't I retrieve all the hashtags from Instagram? when I search for a certain hashtag, the total data is 7000 but when it is scrapped it only gets 4500. Does anyone know about this problem?

**Comment by imnimesh** [comment]
HI, can give me an example how i can scrap the data using hashtag because when i am doing this **instagram-scraper --tag dragonfly** where likes is the hashtag here it is giving me below error 


Searching dragonfly for posts: 0 media [00:00, ? media/s]
Repeated error HTTPError('429 Client Error: - for url: https://www.instagram.com/accounts/login/')
(A)bort, (I)gnore, (R)etry or retry (F)orever?A
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.8.1', 'console_scripts', 'instagram-scraper')())
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 1623, in main
    scraper.scrape_hashtag()
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 443, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 475, in __scrape_query
    disable=self.quiet):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 533, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 552, in __query
    resp = self.get_json(url.format(params))
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 230, in get_json
    resp = self.safe_get(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/instagram_scraper/app.py", line 200, in safe_get
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: - for url: https://www.instagram.com/accounts/login/
Searching dragonfly for posts: 0 media [02:26, ? media/s]

**Comment by AlexNik** [comment]
@imnimesh Try to scrape with login/password.
