### ISSUE TITLE
Cannot import name ConverterMapping

### ISSUE THREAD

**Issue by sgtsilver** [arc298/instagram-scraper#591]
Stopped working for me, didn't update anything.

Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 6, in <module>
    from instagram_scraper.app import main
  File "/home/username/.local/lib/python2.7/site-packages/instagram_scraper/__init__.py", line 1, in <module>
    from instagram_scraper.app import InstagramScraper
  File "/home/username/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 6, in <module>
    import configparser
  File "/home/username/.local/lib/python2.7/site-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping

**Comment by AlexNik** [comment]
Try to use Python 3.6+

**Comment by sgtsilver** [comment]
> Try to use Python 3.6+

I have Python3.7 installed - is there a way to „force“ it? Or should I just uninstall 2.7?

**Comment by sgtsilver** [comment]
> Try to use Python 3.6+

Changed it and it's working again. Thank you!
