### ISSUE TITLE
Please verify your account 

### ISSUE THREAD

**Issue by solkpolk** [arc298/instagram-scraper#598]
When I try running the script I run into a challenge. https://www.instagram.com/challenge/[random_numbers]/[random_letters]/. Even if I pass this test I cannot run the script anymore. Instead, the same test is shown again and again. Tips?

**Comment by solkpolk** [comment]
Used the scraper to scrap 5 accounts, now my account is frozen for 7 days. Is this normal?

**Comment by VasiliPupkin256** [comment]
If you are having this issue often then you need to use `--cookiejar`, see my last comments to #462

**Comment by 501st-alpha1** [comment]
I started getting errors too, and now it presents the challenge, but even if I open the link on the same machine it doesn't work.  I get the prompt every time, and so `instagram-scraper` cannot log in.

Multiple times while trying that I got the pop-up in other places I was logged in, asking "is this you?", and even once or twice forcing me to change my password.

When I login through a browser, I noticed the argument being submitted was called `enc_password`, and the value it had didn't match my password, so maybe Instagram is now encrypting/hashing the password client-side, and that's what's causing this to fail?  If I paste the challenge into a browser, it eventually redirects to `https://www.instagram.com/challenge/?next=/accounts/get_encrypted_credentials/`, which seems to support this.

The format of the argument is as follows:

```
#PWD_INSTAGRAM_BROWSER:10:NUM:HASH
```

Where `NUM` was a 10 digit number, and was similar but not the same across logins, and `HASH` is a 148 character hash that was different each time.  So it looks like there is some kind of salt being applied, so it's not a matter of copying the encrypted password once and using that going forward (though I didn't expect it to be that easy).

My ability to reverse-engineer minimized JavaScript is not super strong, so I haven't figured out how the encrypted password is actually generated yet.  If we are able to figure out how the password is encrypted and duplicate that, then *maybe* that will fix this issue.

**Comment by VasiliPupkin256** [comment]
@501st-alpha1 instaloader use this fancy enc_password authorization, it doesn't save it from this error and account blocks. This number is just a timestamp. I've ported this new kind of authorization to instagram-scraper and used it for some time in a separate branch and I didn't see any changes. I can give you this code so you've able to test it if you like.

**Comment by solkpolk** [comment]
@501st-alpha1 did you try with the `--cookiejar`?

**Comment by 501st-alpha1** [comment]
@solkpolk Yes, I forgot to mention that I have been using `--cookiejar` for quite a while now.

@VasiliPupkin256 Ah okay, that's a bummer.  Yes, I'd be happy to try your branch just to be sure.

**Comment by solkpolk** [comment]
@501st-alpha1 what is the syntax setup for `--cookiejar`? Can't get it to work... :/

**Comment by VasiliPupkin256** [comment]
@501st-alpha1 I've rebased it on some working tree hackery, here it is VasiliPupkin256/instagram-scraper/tree/temp
I've recalled why I was even bother to port this enc_password authorization. I've tried to change useragent to a more recent one and it require this new authorization.

**Comment by 501st-alpha1** [comment]
@solkpolk The syntax is just `--cookiejar <somefile>`; the file doesn't even have to exist, it will be created and written to when you run `instagram-scraper`.  (Though if you're having issues with the challenge and can't log in, it might not be created, I'm not sure.)

@VasiliPupkin256 Thanks!  I'll take a look at it.

**Comment by PatrickeBM** [comment]
can someone help me have the blue instagram stamp even if it is temporary has some script.?

**Comment by vii33** [comment]
Having the same issue as the author. #259 suggests to change the user agents. As soon as I do this I get the `KeyError: "name='csrftoken', domain=None, path=None"` 

-> I tried to use `--cookiejar` to avoid this, but the error still occurs:
```
Traceback (most recent call last):
  File "app.py", line 1540, in main
    scraper.authenticate_with_login()
  File "app.py", line 256, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "...\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "...\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```
Call: `python app.py -u ...  -p ... -n --latest-stamps latest_stamps.txt --media-types image --profile-metadata -f users.txt  --cookiejar cookies.txt`

Do I need to clear a cache or something?

**Comment by oullah** [comment]
I'm running into the same issue: Login failed. Please verify your account at `<link>`. I click the link and verify it's me but it looks like that isn't helping get past the issue. I have tried using `--cookiejar` but the issue seems to be that instagram doesn't like something about the way instagram-scraper is logging in. @VasiliPupkin256 how can I try your branch?

**Comment by VasiliPupkin256** [comment]
@oullah the branch is outdated. I haven't updated it for years and not recommend using it anyway.
