### ISSUE TITLE
AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by zxfrank** [arc298/instagram-scraper#614]
Hello all,

while running `instagram-scraper -t 'image' --cookiejar ../cookies --media-metadata --latest $p` (where $p is the user)
I sometimes get this error. Anyone know why? thanks

```
Traceback (most recent call last):
  File "/home/francis/.local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/home/francis/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 1629, in main
    scraper.scrape()
  File "/home/francis/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 681, in scrape
    self._persist_metadata(dst, username)
  File "/home/francis/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 1361, in _persist_metadata
    self.merge_json({'GraphImages': self.posts}, metadata_path)
  File "/home/francis/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 1322, in merge_json
    self.remove_duplicate_data(file_data[key])
  File "/home/francis/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 1333, in remove_duplicate_data
    file_ids_copy = file_data_ids.copy()
AttributeError: 'list' object has no attribute 'copy'
```

**Comment by Lorenzo-Monaco-EU** [comment]
> Hello all,
> 
> while running `instagram-scraper -t 'image' --cookiejar ../cookies --media-metadata --latest $p` (where $p is the user)
> I sometimes get this error. Anyone know why? thanks
> 
> ```
> Traceback (most recent call last):
>   File "bin/instagram-scraper", line 11, in <module>
>     sys.exit(main())
>   File "lib/python2.7/site-packages/instagram_scraper/app.py", line 1629, in main
>     scraper.scrape()
>   File "lib/python2.7/site-packages/instagram_scraper/app.py", line 681, in scrape
>     self._persist_metadata(dst, username)
>   File "lib/python2.7/site-packages/instagram_scraper/app.py", line 1361, in _persist_metadata
>     self.merge_json({'GraphImages': self.posts}, metadata_path)
>   File "lib/python2.7/site-packages/instagram_scraper/app.py", line 1322, in merge_json
>     self.remove_duplicate_data(file_data[key])
>   File "lib/python2.7/site-packages/instagram_scraper/app.py", line 1333, in remove_duplicate_data
>     file_ids_copy = file_data_ids.copy()
> AttributeError: 'list' object has no attribute 'copy'
> ```

you can use file_ids_copy = list(file_data_ids)
