### ISSUE TITLE
Strange behavior in scraping: no more .mp4 found and tag scraping doesn't work anymore

### ISSUE THREAD

**Issue by basementmilan** [arc298/instagram-scraper#626]
Since this morning everything seems to be ok but know Scraper works only with account media and not tag anymore. Also .mp4 files are not found. 
I'm really not into coding so hoping someone here can help me to find the issue and fix it. 

Here the terminal:

Last login: Fri Nov 20 16:39:09 on ttys000
You have new mail.
MacBook-Pro-di-L:~ leonardog$ instagram-scraper drummachine --tag --maximum 2000
Searching drummachine for posts: 0 media [00:00, ? media/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/instagram-scraper", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.9.1', 'console_scripts', 'instagram-scraper')())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instagram_scraper/app.py", line 1623, in main
    scraper.scrape_hashtag()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instagram_scraper/app.py", line 443, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instagram_scraper/app.py", line 474, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instagram_scraper/app.py", line 533, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/instagram_scraper/app.py", line 555, in __query
    payload = json.loads(resp)['data'][entity_name]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
MacBook-Pro-di-L:~ leonardog$

**Comment by dvschultz** [comment]
Instagram has disabled hashtag search for the election, which is breaking scraping as well.

**Comment by cole8888** [comment]
@dvschultz The election is long over now, why is this still happening?

I can do hashtag searches from within an account.

**Comment by hasibzunair** [comment]
@cole8888 are you able to scrape images from hashtags? Can you explain how? I am getting the same error.

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by cole8888** [comment]
@hasibzunair I was only able to get like 9 images or so from hashtags, I tried other scraping tools too and had the same results.

For my use-case I found I was able to scrape individual accounts rather than hashtags, I needed to be signed into an account though. Make sure you leave some time between scrapes because my dummy accounts kept getting locked up for suspicious activity.

**Comment by hasibzunair** [comment]
@cole8888 how do i leave time between scrapes?

**Comment by cole8888** [comment]
@hasibzunair I just went and did something else for like 15 minutes and then started another scrape.

I bet you could automate it with a python script or something though.

**Comment by AlexNik** [comment]
Add debug output #732
Try to use the instagram-scraper with login credentials.
