### ISSUE TITLE
KeyError: 'GraphStories'

### ISSUE THREAD

**Issue by jasonkhanlar** [arc298/instagram-scraper#632]
I noticed recently some profiles now have a new type of content for downloading, but also just now, for one profile, I see this error appear:

```Traceback (most recent call last):
  File "/usr/bin/instagram-scraper", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.9.1', 'console_scripts', 'instagram-scraper')())
  File "/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 1629, in main
    scraper.scrape()
  File "/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 681, in scrape
    self._persist_metadata(dst, username)
  File "/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 1367, in _persist_metadata
    self.merge_json({'GraphStories': self.stories}, metadata_path)
  File "/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 1322, in merge_json
    self.remove_duplicate_data(file_data[key])
KeyError: 'GraphStories'
```

**Comment by cboussalis** [comment]
I am also experiencing the same error

**Comment by servin** [comment]
any solutions for this?

**Comment by jasonkhanlar** [comment]
I just recompiled and got this error again and I forgot how I fixed it before, but I made this change and it seems to work:

At line 765 https://github.com/arc298/instagram-scraper/blob/master/instagram_scraper/app.py#L765 change it to:

```
            },
            'GraphStories': []
```

**Comment by DevJake** [comment]
I can confirm that I am also receiving this error as well. I hope to try and fix this later on. If my fix is successful, I'll make a pull request for it. However, no promises!

**Comment by phillipshaong** [comment]
I've been getting this error. I looked at line 765, but it has `'external_url': user_info['external_url'],`. Also, I can't find anywhere in the code the line `'GraphStories': []`. Has the change been made? If so, why is the error still occuring? Thanks!

**Comment by servin** [comment]
I'm still getting the same error

**Comment by 89z** [comment]
please provide example URL

**Comment by roncam82** [comment]
was this solved please ? Im still getting the error when adding --latest/--lates-timestamps

thanks
ron

**Comment by AlexNik** [comment]
@roncam82 which version do you use?
Could you attach the output?

**Comment by roncam82** [comment]
any help please ?

**Comment by AlexNik** [comment]
@roncam82 write the full version and the parameters of your run

**Comment by roncam82** [comment]
v1.10.6

f'instagram-scraper "{scrapeusername}" --profile-metadata  --media-metadata --media-types none --latest --cookiejar "C:/Users/""/Desktop/car loan/instagram_cookies" --maximum {postscrapelimit} -u "{username}" -p "{password}" --proxies "{proxies}" --destination {final_path}'):

**Comment by roncam82** [comment]
any updates please ?

**Comment by roncam82** [comment]
@AlexNik found something ?

**Comment by roncam82** [comment]
any update please ?

**Comment by AlexNik** [comment]
Which profile's stories do you try to scrape?
Is this issue occured only with this profile? Does other profiles scrape well or not?

**Comment by roncam82** [comment]
@AlexNik all of the profiles I try.

**Comment by roncam82** [comment]
@AlexNik all the profiles I try. I only need to scrape the latest posts not stories
