### ISSUE TITLE
How long are auth accounts blocked?

### ISSUE THREAD

**Issue by PC-Principal** [arc298/instagram-scraper#642]
How long are auth accounts blocked? I recently accidentally ran the script 2 times at the moment, after which this problem started to appear:

`Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.9.1', 'console_scripts', 'instagram-scraper')()
  File "/usr/local/lib/python3.6/site-packages/instagram_scraper/app.py", line 1607, in main
    scraper.authenticate_with_login()
  File "/usr/local/lib/python3.6/site-packages/instagram_scraper/app.py", line 255, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/usr/local/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

As I understand it, there is a certain problem with cookies, has this cookie been around for a long time?

**Comment by PC-Principal** [comment]
Today I debugged the script in order to get a response from the service in order to understand what causes such an error and found this code:
`{"message": "feedback_required", "spam": true, "feedback_title": "Try Again Later", "feedback_message": "We limit how often you can do certain things on Instagram to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/scraping/", "feedback_appeal_label": "Tell us", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"}`

**Comment by PC-Principal** [comment]
In my case it was 1 day - script now avialable.
