### ISSUE TITLE
Windows version not working

### ISSUE THREAD

**Issue by javiercuadros77** [arc298/instagram-scraper#648]
hello, i'm triyng to use the scraper tool on windows 10 but i allways get errors, tried with python 3.9 and also 3,7 and allways have errored lines, here is the output

on python 3.7

:\Scrap obra\phyton>cd scraper1

D:\Scrap obra\phyton\scraper1>instagram-scraper --tag hola
Searching hola for posts: 0 media [00:00, ? media/s]
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python37\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.9.1', 'console_scripts', 'instagram-scraper')()
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 1623, in main
    scraper.scrape_hashtag()
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 443, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 475, in __scrape_query
    disable=self.quiet):
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\tqdm\std.py", line 1166, in _iter_
    for obj in iterable:
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 533, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 555, in __query
    payload = json.loads(resp)['data'][entity_name]
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\json\_init_.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\usuario\appdata\local\programs\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

and on python 3.9 the following errors
D:\Scrap obra\phyton\scraper1>instagram-scraper --tag hola
Searching hola for posts: 0 media [00:00, ? media/s]
Traceback (most recent call last):
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python39\Scripts\instagram-scraper.exe\_main_.py", line 7, in <module>
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 1623, in main
    scraper.scrape_hashtag()
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 443, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 474, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages\tqdm\std.py", line 1166, in _iter_
    for obj in iterable:
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 533, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 555, in __query
    payload = json.loads(resp)['data'][entity_name]
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\json\_init_.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\usuario\appdata\local\programs\python\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

any idea on how to deal with these? many thanks in advanced

**Comment by AlexNik** [comment]
@javiercuadros77 Try it with login/password parameters

**Comment by javiercuadros77** [comment]
> @javiercuadros77 Try it with login/password parameters

hello Alex, thanks for your answer, i tried with my username + password but now i have my ip blocked :( with error ('429 Client Error: - for url: https://www.instagram.com.....

**Comment by AlexNik** [comment]
@jackmassry I think you have the same like this https://github.com/arc298/instagram-scraper/issues/139 or this https://github.com/arc298/instagram-scraper/issues/607
