### ISSUE TITLE
Two Issues.. Wrong version??

### ISSUE THREAD

**Issue by MrNr2** [arc298/instagram-scraper#656]
I get these Issues:

When i run: python setup.py install

python setup.py install
root@DESKTOP-0B53PJ7:/mnt/c/Users/Me/Desktop/instagram-scraper-master# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to instagram_scraper.egg-info/requires.txt
writing instagram_scraper.egg-info/PKG-INFO
writing top-level names to instagram_scraper.egg-info/top_level.txt
writing dependency_links to instagram_scraper.egg-info/dependency_links.txt
writing entry points to instagram_scraper.egg-info/entry_points.txt
reading manifest file 'instagram_scraper.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'tests'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no files found matching 'README.rst'
writing manifest file 'instagram_scraper.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/instagram_scraper
copying build/lib.linux-x86_64-2.7/instagram_scraper/app.py -> build/bdist.linux-x86_64/egg/instagram_scraper
copying build/lib.linux-x86_64-2.7/instagram_scraper/constants.py -> build/bdist.linux-x86_64/egg/instagram_scraper
creating build/bdist.linux-x86_64/egg/instagram_scraper/tests
copying build/lib.linux-x86_64-2.7/instagram_scraper/tests/test_instagram.py -> build/bdist.linux-x86_64/egg/instagram_scraper/tests
copying build/lib.linux-x86_64-2.7/instagram_scraper/tests/__init__.py -> build/bdist.linux-x86_64/egg/instagram_scraper/tests
copying build/lib.linux-x86_64-2.7/instagram_scraper/__init__.py -> build/bdist.linux-x86_64/egg/instagram_scraper
byte-compiling build/bdist.linux-x86_64/egg/instagram_scraper/app.py to app.pyc
byte-compiling build/bdist.linux-x86_64/egg/instagram_scraper/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/instagram_scraper/tests/test_instagram.py to test_instagram.pyc
byte-compiling build/bdist.linux-x86_64/egg/instagram_scraper/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/instagram_scraper/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying instagram_scraper.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/instagram_scraper-1.8.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing instagram_scraper-1.8.1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/instagram_scraper-1.8.1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/instagram_scraper-1.8.1-py2.7.egg
Extracting instagram_scraper-1.8.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
instagram-scraper 1.8.1 is already the active version in easy-install.pth
Installing instagram-scraper script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/instagram_scraper-1.8.1-py2.7.egg
Processing dependencies for instagram-scraper==1.8.1
Searching for numpy>=1.17.3
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/d2/48/f445be426ccd9b2fb64155ac6730c7212358882e589cd3717477d739d9ff/numpy-1.20.1.zip#sha256=3bc63486a870294683980d76ec1e3efc786295ae00128f9ea38e2c6e74d5a60a
Best match: numpy 1.20.1
Processing numpy-1.20.1.zip
Writing /tmp/easy_install-AXor3A/numpy-1.20.1/setup.cfg
Running numpy-1.20.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-AXor3A/numpy-1.20.1/egg-dist-tmp-w6qAZK
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    keywords=['instagram', 'scraper', 'download', 'media', 'photos', 'videos']
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-AXor3A/numpy-1.20.1/setup.py", line 30, in <module>
    zip_safe=False,
RuntimeError: Python version >= 3.7 required.
root@DESKTOP-0B53PJ7:/mnt/c/Users/me/Desktop/instagram-scraper-master#

and when i run instagram-scraper:

Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'numpy>=1.17.3' distribution was not found and is required by moviepy

**Comment by AlexNik** [comment]
@MrNr2  Try to install Python 3.8+ and run setup with it
