### ISSUE TITLE
json.decoder.JSONDecodeError when scraping for Hashtag

### ISSUE THREAD

**Issue by vordemann** [arc298/instagram-scraper#662]
Did the following request:
`instagram-scraper boijmansdepot --tag`

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/instagram-scraper", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.8.1', 'console_scripts', 'instagram-scraper')())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/instagram_scraper-1.8.1-py3.8.egg/instagram_scraper/app.py", line 1623, in main
    scraper.scrape_hashtag()
  File "/usr/local/anaconda3/lib/python3.8/site-packages/instagram_scraper-1.8.1-py3.8.egg/instagram_scraper/app.py", line 443, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/instagram_scraper-1.8.1-py3.8.egg/instagram_scraper/app.py", line 474, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/usr/local/anaconda3/lib/python3.8/site-packages/instagram_scraper-1.8.1-py3.8.egg/instagram_scraper/app.py", line 533, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/instagram_scraper-1.8.1-py3.8.egg/instagram_scraper/app.py", line 555, in __query
    payload = json.loads(resp)['data'][entity_name]
  File "/usr/local/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by courdek** [comment]
Experiencing the same issue.
```
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/instagram_scraper/app.py", line 1623, in main
    scraper.scrape_hashtag()
  File "/usr/local/lib/python3.9/site-packages/instagram_scraper/app.py", line 443, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/usr/local/lib/python3.9/site-packages/instagram_scraper/app.py", line 474, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "/usr/local/lib/python3.9/site-packages/tqdm/std.py", line 1170, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.9/site-packages/instagram_scraper/app.py", line 533, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "/usr/local/lib/python3.9/site-packages/instagram_scraper/app.py", line 555, in __query
    payload = json.loads(resp)['data'][entity_name]
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by courdek** [comment]
Overcame this by using `--login-user` and `--login-pass`. My suspicion is that IG is redirecting the scraper to the login page which is HTML and thus causing JSON decoding errors.

**Comment by AlexNik** [comment]
Add debug output #732
Try to use the instagram-scraper with login credentials.
