### ISSUE TITLE
Install failed on Termux

### ISSUE THREAD

**Issue by forliuyifei** [arc298/instagram-scraper#667]
```
running install
running bdist_egg
running egg_info
writing instagram_scraper.egg-info/PKG-INFO
writing dependency_links to instagram_scraper.egg-info/dependency_links.txt
writing entry points to instagram_scraper.egg-info/entry_points.txt
writing requirements to instagram_scraper.egg-info/requires.txt
writing top-level names to instagram_scraper.egg-info/top_level.txt
reading manifest file 'instagram_scraper.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'tests'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no files found matching 'README.rst'
writing manifest file 'instagram_scraper.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv8l/egg
running install_lib
running build_py
creating build/bdist.linux-armv8l/egg
creating build/bdist.linux-armv8l/egg/instagram_scraper
copying build/lib/instagram_scraper/constants.py -> build/bdist.linux-armv8l/egg/instagram_scraper
creating build/bdist.linux-armv8l/egg/instagram_scraper/tests
copying build/lib/instagram_scraper/tests/test_instagram.py -> build/bdist.linux-armv8l/egg/instagram_scraper/tests
copying build/lib/instagram_scraper/tests/__init__.py -> build/bdist.linux-armv8l/egg/instagram_scraper/tests
copying build/lib/instagram_scraper/app.py -> build/bdist.linux-armv8l/egg/instagram_scraper
copying build/lib/instagram_scraper/__init__.py -> build/bdist.linux-armv8l/egg/instagram_scraper
byte-compiling build/bdist.linux-armv8l/egg/instagram_scraper/constants.py to constants.cpython-39.pyc
byte-compiling build/bdist.linux-armv8l/egg/instagram_scraper/tests/test_instagram.py to test_instagram.cpython-39.pyc
byte-compiling build/bdist.linux-armv8l/egg/instagram_scraper/tests/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-armv8l/egg/instagram_scraper/app.py to app.cpython-39.pyc
byte-compiling build/bdist.linux-armv8l/egg/instagram_scraper/__init__.py to __init__.cpython-39.pyc
creating build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/PKG-INFO -> build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/SOURCES.txt -> build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/dependency_links.txt -> build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/entry_points.txt -> build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/not-zip-safe -> build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/requires.txt -> build/bdist.linux-armv8l/egg/EGG-INFO
copying instagram_scraper.egg-info/top_level.txt -> build/bdist.linux-armv8l/egg/EGG-INFO
creating 'dist/instagram_scraper-1.8.1-py3.9.egg' and adding 'build/bdist.linux-armv8l/egg' to it
removing 'build/bdist.linux-armv8l/egg' (and everything under it)
Processing instagram_scraper-1.8.1-py3.9.egg
removing '/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper-1.8.1-py3.9.egg' (and everything under it)
creating /data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper-1.8.1-py3.9.egg
Extracting instagram_scraper-1.8.1-py3.9.egg to /data/data/com.termux/files/usr/lib/python3.9/site-packages
instagram-scraper 1.8.1 is already the active version in easy-install.pth
Installing instagram-scraper script to /data/data/com.termux/files/usr/bin

Installed /data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper-1.8.1-py3.9.egg
Processing dependencies for instagram-scraper==1.8.1
Searching for numpy>=1.17.3
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/d2/48/f445be426ccd9b2fb64155ac6730c7212358882e589cd3717477d739d9ff/numpy-1.20.1.zip#sha256=3bc63486a870294683980d76ec1e3efc786295ae00128f9ea38e2c6e74d5a60a
Best match: numpy 1.20.1
Processing numpy-1.20.1.zip
Writing /data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.cfg
Running numpy-1.20.1/setup.py -q bdist_egg --dist-dir /data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/egg-dist-tmp-anjy6sm3
Running from numpy source directory.
/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Cythonizing sources
Processing numpy/random/_bounded_integers.pxd.in
Processing numpy/random/_philox.pyx
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/tools/cythonize.py", line 59, in process_pyx
    from Cython.Compiler.Version import version as cython_version
ModuleNotFoundError: No module named 'Cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/tools/cythonize.py", line 235, in <module>
    main()
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/tools/cythonize.py", line 231, in main
    find_process_files(root_dir)
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/tools/cythonize.py", line 222, in find_process_files
    process(root_dir, fromfile, tofile, function, hash_db)
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/tools/cythonize.py", line 188, in process
    processor_function(fromfile, tofile)
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/tools/cythonize.py", line 64, in process_pyx
    raise OSError('Cython needs to be installed in Python as a module')
OSError: Cython needs to be installed in Python as a module
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py", line 513, in <module>
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py", line 493, in setup_package
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py", line 290, in generate_cython
RuntimeError: Running cythonize failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/GIT/instagram-scraper/setup.py", line 14, in <module>
    setup(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/data/data/com.termux/files/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 714, in install_item
    self.process_distribution(spec, dist, deps)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
    dist = best[req.key] = env.best_match(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/data/data/com.termux/files/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/data/data/com.termux/files/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py", line 513, in <module>
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py", line 493, in setup_package
  File "/data/data/com.termux/files/usr/tmp/easy_install-obdyh1jj/numpy-1.20.1/setup.py", line 290, in generate_cython
RuntimeError: Running cythonize failed!
```

**Comment by AlexNik** [comment]
@forliuyifei Try to install Cython first.
`pip install Cython`

**Comment by forliuyifei** [comment]
> @forliuyifei Try to install Cython first.
> `pip install Cython`
> or
> `pip3 install Cython`

```
~  pip3 install instagram-scraper
Requirement already satisfied: instagram-scraper in /data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper-1.8.1-py3.9.egg (1.8.1)
Requirement already satisfied: requests>=2.18.4 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from instagram-scraper) (2.25.1)
Requirement already satisfied: tqdm>=3.8.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages/tqdm-4.59.0-py3.9.egg (from instagram-scraper) (4.59.0)
Requirement already satisfied: moviepy>=1.0.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages/moviepy-2.0.0.dev2-py3.9.egg (from instagram-scraper) (2.0.0.dev2)
Requirement already satisfied: decorator<5.0,>=4.0.2 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from moviepy>=1.0.0->instagram-scraper) (4.4.2)
Requirement already satisfied: imageio<3.0,>=2.5 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from moviepy>=1.0.0->instagram-scraper) (2.9.0)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from moviepy>=1.0.0->instagram-scraper) (0.4.3)
Requirement already satisfied: numpy>=1.17.3 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from moviepy>=1.0.0->instagram-scraper) (1.20.1)
Requirement already satisfied: proglog<=1.0.0 in /data/data/com.termux/files/usr/lib/python3.9/site-packages/proglog-0.1.9-py3.9.egg (from moviepy>=1.0.0->instagram-scraper) (0.1.9)
Requirement already satisfied: pillow in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from imageio<3.0,>=2.5->moviepy>=1.0.0->instagram-scraper) (8.1.2)
Requirement already satisfied: chardet<5,>=3.0.2 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from requests>=2.18.4->instagram-scraper) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from requests>=2.18.4->instagram-scraper) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from requests>=2.18.4->instagram-scraper) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from requests>=2.18.4->instagram-scraper) (1.26.3)
 ~  instagram-scraper
instagram-scraper: command not found
```

**Comment by AlexNik** [comment]
@forliuyifei try solution from here https://github.com/arc298/instagram-scraper/issues/113
`export PATH=$PATH:~/.local/bin`
