### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by ygqweiwan** [arc298/instagram-scraper#685]
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.8.1', 'console_scripts', 'instagram-scraper')()
  File "/Library/Python/2.7/site-packages/instagram_scraper-1.8.1-py2.7.egg/instagram_scraper/app.py", line 1520, in main
    scraper.authenticate_as_guest()
  File "/Library/Python/2.7/site-packages/instagram_scraper-1.8.1-py2.7.egg/instagram_scraper/app.py", line 236, in authenticate_as_guest
    req = self.session.get(BASE_URL)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x108569ad0>: Failed to establish a new connection: [Errno 60] Operation timed out',))

**Comment by AlexNik** [comment]
I see you use 1.8.1
@ygqweiwan Try to update your lib
