### ISSUE TITLE
`$instagram-scrape --tag` doesn't work  error: IndexError: list index out of range

### ISSUE THREAD

**Issue by monajalal** [arc298/instagram-scraper#705]
(insta) [jalal@goku insta-scrape]$ instagram-scraper --tag fashion
Searching fashion for posts: 0 media [00:02, ? media/s]
Traceback (most recent call last):
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch3/venv/insta/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.10.1', 'console_scripts', 'instagram-scraper')()
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 1548, in main
    scraper.scrape_hashtag()
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 442, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 473, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "/scratch3/venv/insta/lib/python3.8/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 532, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 561, in __query
    nodes.extend(self._get_nodes(top_posts))
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/scratch3/venv/insta/lib/python3.8/site-packages/instagram_scraper/app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range

**Comment by wardrobefanatic** [comment]
Same here. Any help would be appreciated!

**Comment by ketankotak** [comment]
I am getting the same error. any update required?

**Comment by AlexNik** [comment]
Debug output was added #732
Try to use the instagram-scraper with login credentials.
