### ISSUE TITLE
Traceback Errors when running "instagram-scraper <username>" in Terminal (MacOS)

### ISSUE THREAD

**Issue by ghost** [arc298/instagram-scraper#710]
When running the "instagram-scraper <username>" command in the terminal, I am getting a Traceback Error.  However, when I run "instagram-scraper <username> -u <your username> -p <your password>" command, it doesn't seem to download anything. I am not sure if it is on my end or there is a bug in the program.

 - OS: macOS, Linux
 - Python Version:  3.9
 - Terminal: -bash
 - Using cd Desktop as my pathway

Here's the error message I am getting in terminal:

Amnes-MacBook-Pro:Desktop` sniperdron$ instagram-scraper guweiz
Searching guweiz for profile pic: 100% 1/1 [00:00<00:00, 1886.78 images/s]
Searching guweiz for posts: 0 media [00:43, ? media/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/instagram-scraper", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.10.1', 'console_scripts', 'instagram-scraper')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 1554, in main
    scraper.scrape()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 664, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 810, in get_media
    for item in tqdm.tqdm(self.query_media_gen(user), desc='Searching {0} for posts'.format(username),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 921, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 949, in __query_media
    nodes = self._get_nodes(container)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instagram_scraper/app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range

**Comment by primowalker** [comment]
I'm seeing the same issue.

OS: Mac OS Big Sur 11.5.1
Python Version: 3.7.11
Terminal - zsh

instagram-scraper undoinghbo  
Searching undoinghbo for profile pic: 100% 1/1 [00:00<00:00, 3435.14 images/s]
Searching undoinghbo for posts: 0 media [00:01, ? media/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 1554, in main
    scraper.scrape()
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 664, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 811, in get_media
    unit=' media', disable=self.quiet):
  File "/usr/local/lib/python3.7/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 921, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 949, in __query_media
    nodes = self._get_nodes(container)
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/usr/local/lib/python3.7/site-packages/instagram_scraper/app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range

**Comment by mbinkhorst** [comment]
Had the same issues on multiple platforms.  Try logging in with your instagram account, it fixed it for me.

**Comment by AlexNik** [comment]
Debug output was added #732
Try to use the instagram-scraper with login credentials.
