### ISSUE TITLE
List: index out of range 

### ISSUE THREAD

**Issue by Jerukpurut** [arc298/instagram-scraper#711]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instagram-scraper", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.10.1', 'console_scripts', 'instagram-scraper')())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 1554, in main
    scraper.scrape()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 664, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 810, in get_media
    for item in tqdm.tqdm(self.query_media_gen(user), desc='Searching {0} for posts'.format(username),
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 932, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 949, in __query_media
    nodes = self._get_nodes(container)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/instagram_scraper/app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range

It's only scan like 50 photos and that's it 
username= @natwithaheart

**Comment by vectorlit** [comment]
Try logging in.

**Comment by abindadna** [comment]
Hi I also had the same problem related to IndexError: list index out of range

Login is not a solution. because I'm already logged in. I want to scrape the hashtags. But it can't and instead, a notification appears

Traceback (most recent call last):
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abi\AppData\Local\Programs\Python\Python38-32\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 1544, in main
    scraper.scrape_hashtag()
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 442, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 473, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\tqdm\std.py", line 1171, in __iter__
    for obj in iterable:
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 541, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 565, in __query
    nodes.extend(self._get_nodes(posts))
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "c:\users\abi\appdata\local\programs\python\python38-32\lib\site-packages\instagram_scraper\app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range

> Try logging in.

**Comment by tommyct614** [comment]
Change your IP address and try again. Worked for me.

**Comment by AlexNik** [comment]
Debug output was added #732
Try to use the instagram-scraper with login credentials.
