### ISSUE TITLE
Downloading Never Finishes

### ISSUE THREAD

**Issue by XS24X** [arc298/instagram-scraper#712]
As the title says, my downloading progress just stalls/freezes at an early percentage every time. It literally just stays stuck at 11%. I wait 20 minutes and no progress. Is there any way to fix this?

**Comment by zhangzhy2000** [comment]
Got the same issue. 
Logged as "WARNING - Continue after exception PartialContentException('Got first 43756 bytes from 109292') on......"
Slow down the scrapping process just fixed it.

**Comment by VasiliPupkin256** [comment]
Check the .part file created in the destination folder. If it is opened fine then it is caused by #511 PR.

**Comment by zhangzhy2000** [comment]
> Check the .part file created in the destination folder. If it is opened fine then it is caused by #511 PR.

I got something a little bit weird. When I do nothing, the scraper stuck at 0%, logging "WARNING - Continue after exception PartialContentException('Got first 43756 bytes from 109292') on......" again and again.
But, when I added a single line system("pause") as :
`except (requests.exceptions.RequestException, PartialContentException) as e:
                                system("pause")
                                media = url
                                if item['shortcode'] and item['shortcode'] != '':
                                    media += " from https://www.instagram.com/p/" + item['shortcode']
                                if downloaded - downloaded_before > 0:
                                    # if we got some data on this iteration do not count it as a failure
                                    self.logger.warning('Continue after exception {0} on {1}'.format(repr(e), media))
                                    retry = 0 # the next fail will be first in a row with no data
                                    continue`
Though I got a "NameError: name 'system' is not defined" Exception, but the progress bar came to moving.
I also checked that  .part file is opened fine.

**Comment by zhangzhy2000** [comment]
except (requests.exceptions.RequestException, PartialContentException) as e:
                                system("pause")
                                media = url
                                if item['shortcode'] and item['shortcode'] != '':
                                    media += " from https://www.instagram.com/p/" + item['shortcode']
                                if downloaded - downloaded_before > 0:
                                    # if we got some data on this iteration do not count it as a failure
                                    self.logger.warning('Continue after exception {0} on {1}'.format(repr(e), media))
                                    retry = 0 # the next fail will be first in a row with no data
                                    continue

**Comment by zhangzhy2000** [comment]
instagram_scraper.app - DEBUG - Exception in worker thread
Traceback (most recent call last):
  File "c:\users\zhang\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 1118, in download
    raise PartialContentException('Got first {0} bytes from {1}'.format(downloaded, total_length))
instagram_scraper.app.PartialContentException: Got first 192045 bytes from 241515

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\zhang\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 452, in worker_wrapper
    return fn(*args, **kwargs)
  File "c:\users\zhang\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 1128, in download
    system("pause")
NameError: name 'system' is not defined

**Comment by VasiliPupkin256** [comment]
If the .part file is opened fine then it is caused by #511 PR and it should be reverted. @AlexNik 

When you've added a line that caused another exception you've effectively aborted the download of a file, hence the progress moved forward to the next file.

**Comment by zhangzhy2000** [comment]
> If the .part file is opened fine then it is caused by #511 PR and it should be reverted. @AlexNik
> 
> When you've added a line that caused another exception you've effectively aborted the download of a file, hence the progress moved forward to the next file.

Wow that was lucky for me. Thanks a lot.

**Comment by zhangzhy2000** [comment]
> If the .part file is opened fine then it is caused by #511 PR and it should be reverted. @AlexNik
> 
> When you've added a line that caused another exception you've effectively aborted the download of a file, hence the progress moved forward to the next file.

Actually here I got some data. Totally I downloaded 3485 images/videos, 1577 of them are .part, 116 of them are .part with 0 bytes which can't be opened. 
BTW there is no .mp4.part. I don't know what that means.

**Comment by goldfishdillpickle** [comment]
This problem seems to be caused by the following issue #511 which resulted in the following addition to the `app.py` script.

```python
    if content_length is None:
        content_length = response.headers.get('x-full-image-content-length')
```

A temporary solution to this issue would be to locate the `app.py` file and comment out the code above, i.e.

```python
    # if content_length is None:
    #     content_length = response.headers.get('x-full-image-content-length')
```

**Note**: Please be careful because the modification above directly affects an installed package meaning an update of the package in the future will result in your modification being overwritten.
