### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by loretoparisi** [arc298/instagram-scraper#717]
Get this error, at beginning of scrape first item, my command was

```sh
instagram-scraper $1 -m 100 -t image -n -d ./images
```

```sh
Traceback (most recent call last):
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 1550, in main
    scraper.scrape()
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 664, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 811, in get_media
    unit=' media', disable=self.quiet):
  File "/usr/local/lib/python3.7/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 921, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 949, in __query_media
    nodes = self._get_nodes(container)
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/Users/loretoparisi/.pyenv/versions/3.7.10/lib/python3.7/site-packages/instagram_scraper/app.py", line 613, in __get_media_details
    data = resp.split("window.__addi
```

**Comment by liagabrielapagoto** [comment]
i had the same problem

Traceback (most recent call last):
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\liaga\AppData\Local\Programs\Python\Python39\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 1544, in main
    scraper.scrape_hashtag()
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 442, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 473, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\site-packages\tqdm\std.py", line 1185, in __iter__
    for obj in iterable:
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 532, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\site-packages\instagram_scraper\app.py", line 554, in __query
    payload = json.loads(resp)['data'][entity_name]
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\liaga\appdata\local\programs\python\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by invisiblemaker** [comment]
I'm having this issue as well. Has anyone come up with a fix?

**Comment by devanshtyagi150** [comment]
having the same issue on my laptop, was working fine the last few days :(

**Comment by graceyudhaaa** [comment]
is this issue has anything to do with ip ban? i did scrap an instagram account that has a lot of post. some of it was downloaded and then it threw this error. maybe add a time.sleep() between request would've been a fix.

**Comment by SandeepVattapparambil** [comment]
i also had this error

**Comment by 89z** [comment]
same error

**Comment by SandeepVattapparambil** [comment]
I tried the following:

deleted existing instagram-scraper installation completely
installed v1.9.0
then tried scraping,

it works

however, instagram seems to be blocking multiple attempts

**Comment by zv09** [comment]
Agreed...
Having an issue #723
Iam also deinstall instagram-scraper and its prerequisites...
Then using pip3 install it to Python3 area...
Program is working but weird... 
on its runtime it is shown same error as in #723 and locks the IG acc.
But! Still trying to parse posts and metadata from target...
Seems additional args param and parsing posts delay method can help

**Comment by AlexNik** [comment]
Debug output was added #732
Try to use the instagram-scraper with login credentials.
