### ISSUE TITLE
KeyError: 'graphql'

### ISSUE THREAD

**Issue by LastDIce** [arc298/instagram-scraper#728]
I get this error. My command when scraping the media list is 
```
instagram-scraper --login-user MyID --login-pass MyPW --media-metadata --retry-forever --no-check-certificate MyTargetId
```
```
Searching MyTargetId for profile pic: 100% 1/1 [00:00<00:00, 994.62 images/s]
Searching MyTargetId for stories: 100%|#################################################################| 1/1 [00:00<00:00, 994.85 media/s]
Searching MyTargetId for posts: 0 media [00:01, ? media/s]
Traceback (most recent call last):
  File "e:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python37\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 1550, in main
    scraper.scrape()
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 664, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 811, in get_media
    unit=' media', disable=self.quiet):
  File "e:\python37\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 921, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 949, in __query_media
    nodes = self._get_nodes(container)
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "e:\python37\lib\site-packages\instagram_scraper\app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
KeyError: 'graphql'
```

Windows 10 20H2(19042.1237)
Python 3.7.9 (tags/v3.7.9:13c94747c7)
instagrem-scraper 1.10.2

**Comment by nns33213** [comment]
I am using several accounts for instagram-scraper and experienced the issue on one of them (U.S. region). Changing the proxy location doesn't work. Rest of the accounts is currently unaffected, even in the same region.

Here is a "schema" of the response I get: https://snippet.host/zpyh

> update: removing username and pass fixes the issue for me.

@nsater: what do you mean? You cannot use the scraper without username and password.

**Comment by nsater** [comment]
If I use the scrapper with my main username and password it get the 'graphql' error. If I remove it, it works fine. 

I've tried: 
- Changing my password.
- Confirming login activity on Instagram.
- Reinstalled scrapper on a fresh Linux machine.

But, I still have the error.

However, I can change my main Instagram login info to a different account and it works fine, just like you.

Maybe Instagram flagged something on the account?

**Comment by AlexNik** [comment]
Debug output was added #732
Try to use the instagram-scraper with login credentials.

**Comment by muhammadrofiq** [comment]
i have same issue. if its already fixed ?

**Comment by AlexNik** [comment]
@muhammadrofiq Could you upgrade to 1.10.3 and post here your output and console parameters?

**Comment by nns33213** [comment]
Why close the issue? It's not fixed. "New" schema is here: https://snippet.host/zpyh

**Comment by AlexNik** [comment]
@nns33213  I closed this issue because I haven't reproduced it.
So, in 1.10.3 I've added more debug output for debugging issues like this.
If you have the same error upgrede to 1.10.3 please and open new issue with the error output.
Thanks for "new" schema.

**Comment by novitae** [comment]
I fixed it for good [here](https://github.com/arc298/instagram-scraper/issues/741) because it seems developers doesn't have the time to at least check what the api response is when this errors happens
