### ISSUE TITLE
Hashtag search throws exception

### ISSUE THREAD

**Issue by shannontesla** [arc298/instagram-scraper#734]
Inside my terminal I've written: `'instagram-scraper wine --tag`.

The following error arose:

`
Searching wine for posts: 0 media [00:03, ? media/s]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 610, in __get_media_details
    return json.loads(resp)['graphql']['shortcode_media']
  File "/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 1544, in main
    scraper.scrape_hashtag()
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 442, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 473, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "/opt/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 532, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 561, in __query
    nodes.extend(self._get_nodes(top_posts))
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/opt/anaconda3/lib/python3.8/site-packages/instagram_scraper/app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range`

**Comment by ivanlengyel** [comment]
I have the same error when I try to search using `--tag`.

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mlizhardy** [comment]
same

**Comment by persac** [comment]
Same here, the --tag option seems to be broken.
