### ISSUE TITLE
KeyError: 'graphql' still happening (1.10.3)

### ISSUE THREAD

**Issue by smoofra** [arc298/instagram-scraper#739]
**Describe the bug**
instagram-scraper crashes with `KeyError: 'graphql'`

**To Reproduce**
```
odin:~$ /usr/local/bin/instagram-scraper  -v 2   --latest --cookiejar $HOME/.instagram-cookies  catbarf2000 -u  smoofra -p $password -d /data/Backup/julie-instagram
Searching catbarf2000 for profile pic: 100% 1/1 [00:00<00:00, 1343.47 images/s]
Searching catbarf2000 for stories: 0 media [00:00, ? media/s]
Searching catbarf2000 for posts: 0 media [00:00, ? media/s]
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 1560, in main
    scraper.scrape()
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 674, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 820, in get_media
    for item in tqdm.tqdm(self.query_media_gen(user), desc='Searching {0} for posts'.format(username),
  File "/usr/local/lib/python3.9/dist-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 931, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 959, in __query_media
    nodes = self._get_nodes(container)
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 579, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 579, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 597, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/home/lawrence_danna/.local/lib/python3.9/site-packages/instagram_scraper/app.py", line 620, in __get_media_details
    return j['graphql']['shortcode_media']
KeyError: 'graphql'
```

**Expected behavior**
doesn't crash.

**System (please complete the following information):**
 - OS: ubuntu 21.10
 - Python Version: 3.9.7
 - instagram-scraper version: 1.10.3

**Comment by smoofra** [comment]
previous isssue was here: https://github.com/arc298/instagram-scraper/issues/728#issuecomment-968154185

**Comment by novitae** [comment]
I fixed it for good [here](https://github.com/arc298/instagram-scraper/issues/741) because it seems developers doesn't have the time to at least check what the api response is when this errors happens
