### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ivanlen** [arc298/instagram-scraper#745]
Either using the docker image or installing the repo using pip returns the following error:
```
Traceback (most recent call last):
  File "instagram_scraper/app.py", line 1563, in <module>
    main()
  File "instagram_scraper/app.py", line 1551, in main
    scraper.scrape_hashtag()
  File "instagram_scraper/app.py", line 449, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "instagram_scraper/app.py", line 480, in __scrape_query
    for item in tqdm.tqdm(media_generator(value), desc='Searching {0} for posts'.format(value), unit=" media",
  File "/usr/local/lib/python3.8/site-packages/tqdm-4.62.3-py3.8.egg/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "instagram_scraper/app.py", line 539, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "instagram_scraper/app.py", line 561, in __query
    payload = self._get_json(resp)['data'][entity_name]
  File "instagram_scraper/app.py", line 159, in _get_json
    return json.loads(text)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by AlexNik** [comment]
@ivanlen How do you run it?
Which version do you use?

**Comment by ivanlen** [comment]
python 3.7.9
instagram-scraper         1.10.3
`instagram-scraper seaplane --tag --maximum 1000`

or builded from latest master with docker

`docker run -it --rm -v $(pwd)/data:/instagram-scraper/data instagram-scraper -i -d data/test seaplane --tag`

**Comment by AlexNik** [comment]
@ivanlen Is it the full output?
Do you have something above it?
Try to scrape with you login credentials.

**Comment by philtyphils** [comment]
I got same error.

**Comment by caas1729** [comment]
I received the same reason as well, using Python 3.10.0 and instagram-scraper 1.10.3. I used the command: ```instagram-scraper hildaandjessesf --media-metadata --profile-metadata --comments --include-location```.

**Comment by alirezabhr** [comment]
I am getting same error when I want to logout
