### ISSUE TITLE
[FIXED] please help for this error (KeyError: "name='csrftoken', domain=None, path=None")

### ISSUE THREAD

**Issue by Felzow47** [arc298/instagram-scraper#752]
hello ?
why i have this error 

Traceback (most recent call last):
  File "/home/debian/pythonenv/pythonenv/bin/instagram-scraper", line 10, in <module>
    sys.exit(main())
  File "/home/debian/pythonenv/pythonenv/lib/python3.7/site-packages/instagram_scraper/app.py", line 1535, in main
    scraper.authenticate_with_login()
  File "/home/debian/pythonenv/pythonenv/lib/python3.7/site-packages/instagram_scraper/app.py", line 256, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/home/debian/pythonenv/pythonenv/lib/python3.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/debian/pythonenv/pythonenv/lib/python3.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by edumarmar** [comment]
Same here!

**Comment by Felzow47** [comment]
after reinstalling python and insta scraper it works !

**Comment by Felzow47** [comment]
this fucking error get back I'm not going to have fun uninstalling reinstall python every day -_-

**Comment by 89z** [comment]
can you provide the code you used?

**Comment by alirezabhr** [comment]
Hi, I have this problem too. I found the problem but I don't know how can I fix it.
This problem cause in "authenticate_with_login" method:
`
        login = self.session.post(LOGIN_URL, data=login_data, allow_redirects=True)
        self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})` 

here when post request got 429 (Too Many Requests) instead of 200, login.cookies does not have "csrftoken" key.

**Comment by AlexNik** [comment]
@alirezabhr how do you run it?
Do you use any loops?

**Comment by alirezabhr** [comment]
no I didn't call this method in any loops. but I'd called this function more than 10times manual

**Comment by AlexNik** [comment]
@alirezabhr don't login so much times.
Use cookies from previous sessions.

**Comment by alirezabhr** [comment]
Is there any difference if I logout every time after scrape finished?

**Comment by AlexNik** [comment]
Unfortunately I don't know.
I suppose yes.
But I recommend to use cookies instead login every time.

**Comment by alirezabhr** [comment]
Do you know how long can I use each cookie?

**Comment by AlexNik** [comment]
I don't test this (
I suppose one day.

**Comment by alirezabhr** [comment]
Hi again. how can I use my previous cookies?
I've tried like the following but not worked for me:
`def set_cookie(self, cookie_dict):
      self.session.headers.update({'Referer': BASE_URL, 'user-agent': CHROME_WIN_UA})
      self.session.headers.update({'X-CSRFToken': cookie_dict.get('csrftoken')})
      self.cookies = cookie_dict`
   
`scraper.set_cookie(cookie_dict)`
cookie_dict is the cookie which I got from last login.

**Comment by mb9023** [comment]
I'm getting this error suddenly now too. My command is simply
`instagram-scraper -u $user -p $pwd --destination $dest -n --cookiejar cookies.txt --interactive -f igs.txt -t image video story --latest`

Only runs against about 6 different ig accounts twice a day from a cron script. One of the runs was fine but the other did not run, now every time I try to run manually I get the same error in the top post.

**Comment by nns33213** [comment]
@mb9023 just try a different VPN/proxy or wait some time. It's rate limiting - not something you'll be able to fix on your end.

> @alirezabhr don't login so much times.
> Use cookies from previous sessions.

@AlexNik that happens even when you use cookiejar. I think there's something wrong with the cookiejar logic.

**Comment by mb9023** [comment]
Unfortunately if I try VPNs it keeps going to Login Failed and giving me a login challenge link even though I keep saying "this was me" it never starts working.

**Comment by AlexNik** [comment]
> @AlexNik that happens even when you use cookiejar. I think there's something wrong with the cookiejar logic.

I see. I'm confused with this logic because this code was not written by me.
Try the first run like this
`instagram-scraper -u $user -p $pwd --cookiejar cookies.txt ...` with optional `-i`
The others
`instagram-scraper --cookiejar cookies.txt ...`
@nns33213 Write the result please.

**Comment by nns33213** [comment]
@AlexNik if I run the second command without `-u` and `-p`, it gives me

```
ERROR: Error getting user details for <user1>. Please verify that the user exists.
ERROR: Error getting user details for <user2>. Please verify that the user exists.
ERROR: Error getting user details for <user3>. Please verify that the user exists.
```

and so on...

In order for it to work, I have to specify the username and password with cookiejar and I think it still does the login on every run. I'm pretty sure that's not how it's supposed to work.

**Comment by 0xFFD** [comment]
Getting same error as @nns33213, tried to run without -u and -p parameters but result is same as him.

**Comment by AlexNik** [comment]
I will try to check this issue next week.

**Comment by YuraYelisieiev** [comment]
@AlexNik same issue with all of the parameters provided by you.

**Comment by mb9023** [comment]
still having this issue, script is basically useless now. I'm able to scrape some other accounts with 'instaloader' program instead using my same login so I might try to switch to that instead.

**Comment by gudaocode** [comment]
This problem did not occur a few days ago, and it was no problem when I started crawling today, and then it appeared, and now the problem has reappeared.
Traceback (most recent call last):
  File "c:\users\*****\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\*****\appdata\local\programs\python\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\*****\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 1575, in main
    scraper.authenticate_with_login()
  File "c:\users\*****\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 272, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "c:\users\*****\appdata\local\programs\python\python310\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "c:\users\*****\appdata\local\programs\python\python310\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
