### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tobiasbenkner** [arc298/instagram-scraper#761]
Hi, 

I am using the latest Docker Image. The container was working last week. Today it's broken. My Instragram account is still working and is not blocked. But today I get an error message `KeyError: 'graphql'`. I tried it with different profiles.

***Command***
```
docker run --rm -v $(pwd)/datalake/instagram:/instagram-scraper/data alexnik/instagram-scraper -i -d data --media-metadata --profile-metadata --media-types none --login-user "username" --login-pass "password" --template "{date}-{h}{m}{s}-{shortcode}-{mediatype}" instagram_user
```

***Error***
````
Traceback (most recent call last):
  File "instagram_scraper/app.py", line 1563, in <module>
    main()
  File "instagram_scraper/app.py", line 1557, in main
    scraper.scrape()
  File "instagram_scraper/app.py", line 671, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "instagram_scraper/app.py", line 817, in get_media
    for item in tqdm.tqdm(self.query_media_gen(user), desc='Searching {0} for posts'.format(username),
  File "/usr/local/lib/python3.8/site-packages/tqdm-4.62.3-py3.8.egg/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "instagram_scraper/app.py", line 928, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "instagram_scraper/app.py", line 956, in __query_media
    nodes = self._get_nodes(container)
  File "instagram_scraper/app.py", line 579, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "instagram_scraper/app.py", line 579, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "instagram_scraper/app.py", line 597, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "instagram_scraper/app.py", line 617, in __get_media_details
    return self._get_json(resp)['graphql']['shortcode_media']
KeyError: 'graphql'
````

**Comment by AlexNik** [comment]
@tobiasbenkner Hello!
I think you have the bug wich was fixed here
https://github.com/arc298/instagram-scraper/pull/760
I merged it today.
I'll try to release new version tonight.

**Comment by AlexNik** [comment]
@tobiasbenkner I've updated.
Try 1.10.4 version.

**Comment by tobiasbenkner** [comment]
@AlexNik perfect! it works 🚀 thanks a lot!
