### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Turkmen1Mehmet** [arc298/instagram-scraper#764]
Why am I getting this error?

Searching **** for posts: 300 media [01:22,  3.65 media/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 1576, in main
    scraper.scrape()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 690, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 837, in get_media
    unit=' media', disable=self.quiet):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 958, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 975, in __query_media
    nodes = self._get_nodes(container)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 579, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 579, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 598, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 635, in __get_media_details
    return self._get_json(resp)['graphql']['shortcode_media']
TypeError: list indices must be integers or slices, not str

**Comment by AlexNik** [comment]
@Turkmen1Mehmet which version do you use?

**Comment by Turkmen1Mehmet** [comment]
1.10.4 version

**Comment by nns33213** [comment]
Yep, this is the same as #728 but different error appears for some people. Fixed in https://github.com/arc298/instagram-scraper/pull/762/commits/c0beb44ff6f143b5e88839cda13b99df76e772fd

**Comment by VasiliPupkin256** [comment]
@nns33213 I've commented under the commit, not sure where is it posted and have you seen it. Error reported here and in #765 is different. Instagram sometimes returns specially formatted json. Which is either a list of a dictionary with two fields message and status. I've seen it for a wile and even started making patch to get_json function but suddenly the error disappear and I haven't finish.

**Comment by nns33213** [comment]
> Error reported here and in #765 is different.
@VasiliPupkin256 You mean #728? I know #765 is different.

To be honest I got it from https://github.com/arc298/instagram-scraper/pull/742/files/30a6cd571b60713480d8e0205c2741b57ef31672#diff-3dc8309da52b06c6075015b7ad56503c26fdbca1ff71ed356a0e196769f0158eR610

I could not figure out why @novitae included the TypeError so I excluded it from my commit. I thought I perhaps overlooked something and this is issue the aftermath of it. But you are correct, this was most likely his attempt of fixing it.

**Comment by AlexNik** [comment]
@VasiliPupkin256 I dream to add something like "full" logging of web requests/responses and add "safe" operator [] for fixing bugs like this.

**Comment by novitae** [comment]
> Why am I getting this error?

You could help by showing us the json response you get that creates this error.\
Go in instagram_scraper/app.py, line 635, and replace:
```python
return self._get_json(resp)['graphql']['shortcode_media']
```
by
```python
resp = self._get_json(resp)
with open("wtfisthisjson.json","w") as f:
     f.write(json.dumps(resp,indent=4)
return resp['graphql']['shortcode_media']
```
and paste us the content of "wtfisthisjson.json" (try to edit it to remove sensitive informations on the account you targeted if you can before pasting it here).

**Comment by FatemeKhodayari** [comment]
I'm having the same issue. Checking the `self._get_json(resp)` it seems that Instagram is having issue with rate limit and asking me to wait for a while and then try again.
