### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by RithikChoudhary** [arc298/instagram-scraper#765]
I have tried so many different instagram public userID , but it shows this error list index out of range if they have posted any video or reels 
please help me regarding this issue , I think its a bug 

`
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 1554, in main
    scraper.scrape()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 664, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 810, in get_media
    for item in tqdm.tqdm(self.query_media_gen(user), desc='Searching {0} for posts'.format(username),
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 921, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 949, in __query_media
    nodes = self._get_nodes(container)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 572, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 572, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 590, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\instagram_scraper\app.py", line 613, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range`

**Comment by devenblake** [comment]
Can reproduce, installed via pip.

**Comment by RithikChoudhary** [comment]
@devenblake  I didn't get it , what does it mean

**Comment by zhav1k** [comment]
hello, I'm getting the same error. Is there any solution?

**Comment by VasiliPupkin256** [comment]
Those who get this error are ratelimited most likely. This error could have a better diagnostics but you would have to wait or use another account anyway.

**Comment by VasiliPupkin256** [comment]
If anyone here who get this error and is experienced in programming, can you please find the scraper app.py file somewhere in the python/Lib/site-packages folder, change the get_json function to this code and rerun the scraper

    def get_json(self, *args, **kwargs):
        """Retrieve text from url. Return text as string or None if no data present """
        resp = self.safe_get(*args, **kwargs)
        
        if resp is not None:
            text = resp.text
            try:
                j = json.loads(text)
                err = ""
                if isinstance(j, list):
                    err = err + "[array] "
                    j = j[0]
                if isinstance(j, str):
                    err = err + "[string] "
                    j = json.loads(j)
                if j['status'] == "fail":
                    self.logger.error(err + j["message"])
                    return None
            except:
                pass
            return text

**Comment by HanjoYoutaku** [comment]
Resolved for me by supplying -u and -p.

**Comment by Lxand3r** [comment]
> Resolved for me by supplying -u and -p.

Hi can you please explain step by step hahaha  seriously plz

**Comment by VasiliPupkin256** [comment]
Ok, I've able to catch the issue. The server response is `["{\"message\":\"Please wait a few minutes before you try again.\",\"status\":\"fail\"}"]` and the code above works. But the log is now full of messages:

    ...
    ERROR - Please wait a few minutes before you try again.
    WARNING - Failed to get media details for XXXXXXX
    ERROR - Please wait a few minutes before you try again.
    WARNING - Failed to get media details for XXXXXXX
    ...

So, it fails to download posts but still continue to scrape stories. Is this behavior is what we expect from it, or should we abort the scrapping?
