### ISSUE TITLE
Error in lines 33, 157, 272, 328, 399

### ISSUE THREAD

**Issue by djmarioka** [arc298/instagram-scraper#777]
Hi,

it's giving these errors , in lines 33, 157, 272, 328, 399, I attach a screenshot:

![image](https://user-images.githubusercontent.com/81478245/154864089-88583f74-15ac-4109-939a-f3e83f75daff.png)

Could you fix this issue?.

Thanks.

**Comment by AlexNik** [comment]
@djmarioka try to update to 1.10.5

**Comment by gudaocode** [comment]
I have updated to 1.10.6 ,but still:
Traceback (most recent call last):
File "c:\users*\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users*\appdata\local\programs\python\python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\Users*****\AppData\Local\Programs\Python\Python310\Scripts\instagram-scraper.exe_main.py", line 7, in
File "c:\users*\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 1575, in main
scraper.authenticate_with_login()
File "c:\users*\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 272, in authenticate_with_login
self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
File "c:\users*\appdata\local\programs\python\python310\lib\site-packages\requests\cookies.py", line 328, in getitem
return self._find_no_duplicates(name)
File "c:\users*\appdata\local\programs\python\python310\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
