### ISSUE TITLE
Already updated to 1.10.6，but err “KeyError: "name='csrftoken', domain=None, path=None"” Still

### ISSUE THREAD

**Issue by gudaocode** [arc298/instagram-scraper#784]
instagram-scraper 1.10.6
Windows 11
python 3.10

Traceback (most recent call last):
  File "c:\users\**\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\**\appdata\local\programs\python\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\**\AppData\Local\Programs\Python\Python310\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\**\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 1575, in main
    scraper.authenticate_with_login()
  File "c:\users\**\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 272, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "c:\users\**\appdata\local\programs\python\python310\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "c:\users\**\appdata\local\programs\python\python310\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by nns33213** [comment]
It doesn't matter what the version is. This is Instagram rate-limiting. Use a different proxy or VPN.

**Comment by gudaocode** [comment]
Thank you！
