### ISSUE TITLE
No longer working after 1 day, Python error regarding csrftoken

### ISSUE THREAD

**Issue by toastking42** [arc298/instagram-scraper#787]
I have downloaded and successfully tested instagram-scraper. All media was downloaded successfully. After that, I configured instagram-scraper to run as a scheduled task on an hourly basis.
However, after about a day, it stopped working completely. Now even if running manually, I just get the following output. Omitting all of the optional arguments doesn't help and omitting username and password results in a different error and also doesn't work even though I'm scraping a public profile. I have changed nothing since it worked. What's going on here? Running on Windows 11. The logfile is empty.

The credentials are valid, I'm still able to use the profile on my phone.

```
PS C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts> instagram-scraper NameOfUserToScrape -u USER -p PW -d "D:\instagram" -n --latest-stamps "D:\instagram\lastrun.txt" --cookiejar "D:\instagram\cookies.txt"
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagram_scraper\app.py", line 1575, in main
    scraper.authenticate_with_login()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instagram_scraper\app.py", line 272, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by nns33213** [comment]
@toastking42 that just means IP is rate limited. Try a different IP address.

BTW. running on a hourly basis with a single account is going to get you banned quickly IMO.

**Comment by toastking42** [comment]
Thanks! It really seems to have been a temporary problem. Quite weird, since my smartphone (same IP address) was able to access the account in question just fine and I configured instagram-scraper to use a cookie cache. However, I have reduced my script to only run once a day.
