### ISSUE TITLE
 a new error  IndexError: list index out of range

### ISSUE THREAD

**Issue by gudaocode** [arc298/instagram-scraper#790]
Searching milkcocoa_official for profile pic: 100% 1/1 [00:00<?, ? images/s]
Searching milkcocoa_official for stories: 100%|##############################################| 3/3 [00:00<?, ? media/s]
Searching milkcocoa_official for posts: 0 media [00:00, ? media/s]ERROR: Text is not json: for (;;);{"__ar":1,"error":1357004,"errorSummary":"\u5f88\u62b1\u6b49\uff0c\u53d1\u751f\u9519\u8bef","errorDescription":"\u8bf7\u5c1d\u8bd5\u5173\u95ed\u6d4f\u89c8\u5668\u7a97\u53e3\uff0c\u7136\u540e\u91cd\u65b0\u5f00\u542f\u3002","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005289518}}},"lid":"7081878349506324818"}
Searching milkcocoa_official for posts: 0 media [00:01, ? media/s]
Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 652, in __get_media_details
    return self._get_json(resp)['graphql']['shortcode_media']
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 159, in _get_json
    return json.loads(text)
  File "c:\users\***\appdata\local\programs\python\python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\***\appdata\local\programs\python\python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\***\appdata\local\programs\python\python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\***\appdata\local\programs\python\python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 1597, in main
    scraper.scrape()
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 706, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 852, in get_media
    for item in tqdm.tqdm(self.query_media_gen(user), desc='Searching {0} for posts'.format(username),
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 963, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 991, in __query_media
    nodes = self._get_nodes(container)
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 593, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 593, in <listcomp>
    return [self.augment_node(node['node']) for node in container['edges']]
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 612, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "c:\users\***\appdata\local\programs\python\python310\lib\site-packages\instagram_scraper\app.py", line 655, in __get_media_details
    data = resp.split("window.__additionalDataLoaded(")[1].split("});</script>")[0].split('{"graphql":')[1]
IndexError: list index out of range

**Comment by AlexNik** [comment]
Very intetesting
IF you decode and translate `errorSummary` and `errorDescription`

```
很抱歉，发生错误
请尝试关闭浏览器窗口，然后重新开启。
```

```
Sorry, an error occurred
Please try closing the browser window and then opening it again.
```

May be you have reached the rate limit...

**Comment by gudaocode** [comment]
Thank you, there are more and more bans now.

**Comment by kapil12k** [comment]
@gudaocode @AlexNik did we figure out a solution to this problem? I'm facing the same issue.

**Comment by AlexNik** [comment]
Unfortunatly, no (
Do you have the same error text in `errorSummary` field?
