### ISSUE TITLE
KeyError: 'GraphImages'

### ISSUE THREAD

**Issue by victoryy2003** [arc298/instagram-scraper#791]
These are the command line parameters I used:
`instagram-scraper %USERNAME% --destination %DESTINATION% --login-user %LOGIN_USER% --login-pass %LOGIN_PASS% --filename %FILENAME% --retain_username --media-metadata --profile-metadata --include-location --latest --cookiejar cookieJar --comments --interactive --retry-forever --template %TEMPLATE% --log_destination %LOG_DESTINATION%`

I found out when I try to download a single post with several images or videos, it will only download the first image, but when it try to download the second image will throw out `KeyError: 'GraphImages'`, and only the first image had been downloaded

```
Searching somebody for profile pic: 100% 1/1 [00:00<00:00, 998.64 images/s]
Searching somebody for stories: 0 media [00:00, ? media/s]
Searching somebody for posts: 1 media [00:02,  2.12s/ media]
Downloading: 100%|#############################################################################################################################| 2/2 [00:00<00:00,  3.02it/s]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Sources\Python\Python310\Scripts\instagram-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('instagram-scraper==1.10.6', 'console_scripts', 'instagram-scraper')())
  File "C:\Users\User\Documents\Sources\Python\Python310\lib\site-packages\instagram_scraper-1.10.6-py3.10.egg\instagram_scraper\app.py", line 1597, in main
    scraper.scrape()
  File "C:\Users\User\Documents\Sources\Python\Python310\lib\site-packages\instagram_scraper-1.10.6-py3.10.egg\instagram_scraper\app.py", line 721, in scrape
    self._persist_metadata(dst, username)
  File "C:\Users\User\Documents\Sources\Python\Python310\lib\site-packages\instagram_scraper-1.10.6-py3.10.egg\instagram_scraper\app.py", line 1324, in _persist_metadata
    self.merge_json({'GraphImages': self.posts}, metadata_path)
  File "C:\Users\User\Documents\Sources\Python\Python310\lib\site-packages\instagram_scraper-1.10.6-py3.10.egg\instagram_scraper\app.py", line 1285, in merge_json
    self.remove_duplicate_data(file_data[key])
KeyError: 'GraphImages'
```
 #632 

OS: Windows 11
Python Version: 3.10.4

**Comment by most2279** [comment]
I'm running into the exact same error. This has not yet occurred in January. What has changed?
