### ISSUE TITLE
I have no clue how to login + How can i make the bot only target reels

### ISSUE THREAD

**Issue by MMJv3** [arc298/instagram-scraper#796]
Every time i try to login i get this.

instagram-scraper -u (username I put here)-p (password here)

outputs this

Traceback (most recent call last):
  File "C:\Users\majes\AppData\Local\Programs\Python\Python37\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.10.6', 'console_scripts', 'instagram-scraper')()
  File "C:\Users\majes\AppData\Local\Programs\Python\Python37\lib\site-packages\instagram_scraper-1.10.6-py3.7.egg\instagram_scraper\app.py", line 1535, in main
    raise ValueError('Must provide username(s) OR a file containing a list of username(s) OR pass --followings-input')
ValueError: Must provide username(s) OR a file containing a list of username(s) OR pass --followings-input

**Comment by AlexNik** [comment]
@MMJv3 You forgot to pass a target user for scraping.
