### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by qiankunxienb** [arc298/instagram-scraper#799]
just when I execute `instagram-scraper target_user -u myusername -p mypassword`

```
Traceback (most recent call last):
  File "/Users/kingname/.local/share/virtualenvs/instagram-KYZazQ_N/bin/instagram-scraper", line 8, in <module>
    sys.exit(main())
  File "/Users/kingname/.local/share/virtualenvs/instagram-KYZazQ_N/lib/python3.9/site-packages/instagram_scraper/app.py", line 1575, in main
    scraper.authenticate_with_login()
  File "/Users/kingname/.local/share/virtualenvs/instagram-KYZazQ_N/lib/python3.9/site-packages/instagram_scraper/app.py", line 268, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/Users/kingname/.local/share/virtualenvs/instagram-KYZazQ_N/lib/python3.9/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Users/kingname/.local/share/virtualenvs/instagram-KYZazQ_N/lib/python3.9/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by nns33213** [comment]
Another one https://github.com/arc298/instagram-scraper/pull/788

Try with a different IP address, VPN or proxy.

**Comment by qiankunxienb** [comment]
Yes, it is the problem of IP. When I use proxy, it works like a charm.

**Comment by roncam82** [comment]
what proxy are you using because im having the same error ?
