### ISSUE TITLE
help error cannot use instascrape !!

### ISSUE THREAD

**Issue by roncam82** [arc298/instagram-scraper#811]
**Describe the bug**
Traceback (most recent call last):
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\Scripts\instagram-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\lib\site-packages\instagram_scraper\app.py", line 1575, in main
    scraper.authenticate_with_login()
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\lib\site-packages\instagram_scraper\app.py", line 272, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Ronald\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**To Reproduce**
instagram-scraper crossfitmotivationdailyy -u ****** -p **** -i --cookiejar "C:\Users\**\Desktop\**\cookies.jar" --proxies "{""http"": ""http://43.250.127.98:9001""}"

**Comment by nns33213** [comment]
@roncam use a different VPN or proxy: https://github.com/arc298/instagram-scraper/pull/788

**Comment by roncam82** [comment]
> @RonCam use a different VPN or proxy: #788

Can you suggest me some free ones ?
