### ISSUE TITLE
csrftoken not found

### ISSUE THREAD

**Issue by a-chess** [arc298/instagram-scraper#856]
**Describe the bug**

csrftoken not found

```py
def authenticate_as_guest(self):
        """Authenticate as a guest/non-signed in user"""
        self.session.headers.update({'Referer': BASE_URL, 'user-agent': STORIES_UA})
        req = self.session.get(BASE_URL)

        self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
```

I was able to get TOKEN by changing as follows

```py
req = self.session.get('https://i.instagram.com/api/v1/public/landing_info/')
self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
```

It seemed that the reason was that the set_cookie attribute was removed from the response of base_url and set_cookie was set to /api/v1/public/landing_info instead.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/7105360/198514555-33cf60e8-9ba2-4756-b941-6c81fc4f7983.png">

**Comment by trsmith78** [comment]
I tried your suggestion, but still having the same issue.  Is yours still working?

**Comment by a-chess** [comment]
It is working in my environment as of 11/1/2022.

IP may be rate-limited.
Try using a proxy or running on a VM.

**Comment by trsmith78** [comment]
#

> It is working in my environment as of 11/1/2022.
> 
> IP may be rate-limited. Try using a proxy or running on a VM.

Hey.  I created a vm and that didn't work.  I also tried with vpn, obfuscated, double vpn.  Still getting the same issue.  What agent are you using?

**Comment by dfwdraco76** [comment]
Trying to get this working for the first time, and I keep running into this csrf error
`Traceback (most recent call last):
  File "/home/dfwdraco76/.local/lib/python3.10/site-packages/instagram_scraper/app.py", line 1554, in main
    scraper.authenticate_with_login()
  File "/home/dfwdraco76/.local/lib/python3.10/site-packages/instagram_scraper/app.py", line 267, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
`
I've tried numerous VPN servers with no luck.

**Comment by osluf** [comment]
Same here.

**Comment by adrian-izdebski-lrn** [comment]
Workaround works, `BASE_URL` no longer gives you  
```
>>> session = requests.Session()
>>> BASE_URL = 'https://www.instagram.com/'
>>> STORIES_UA = 'Instagram 123.0.0.21.114 (iPhone; CPU iPhone OS 11_4 like Mac OS X; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/605.1.15'
>>> req = session.get(BASE_URL)
>>> req.cookies.get_dict()
{}

>>> session2 = requests.Session()
>>> req_not_base = session2.get("https://i.instagram.com/api/v1/public/landing_info/")
>>> req_not_base.cookies.get_dict().get("csrftoken")
'KHj5kWiPVwLnmPcuVMCW81zU2YgGcSX2'
```

**Comment by iuooip** [comment]
Workaround is valid, `BASE_URL` no longer gives you `csrftoken`
```
>>> session = requests.Session()
>>> BASE_URL = 'https://www.instagram.com/'
>>> req = session.get(BASE_URL)
>>> req.cookies.get_dict()
{}

>>> session2 = requests.Session()
>>> req_not_base = session2.get("https://i.instagram.com/api/v1/public/landing_info/")
>>> req_not_base.cookies.get_dict().get("csrftoken")
'KHj5kWiPVxxx'
```
